
<p style="font-size:50px">
<span style="font-size:200px">
&#9703;
</span>
Pandas
</p>

---

### Pandas

La librairie [Pandas](https://pandas.pydata.org/) est une librairie d'analyse de données utilisée pour manipuler des données tabulaires.

Sous-sections :
[Séries et DataFrames](#dataframes)&nbsp;|
[Index](#index)&nbsp;|
[Sélections et projections](#selection)&nbsp;|
[Réorganiser les données](#reorganiser)&nbsp;|
[Exercices](#exercices)&nbsp;

<a id="dataframes"></a>
### Séries et DataFrames

On importe généralement le module Pandas de la manière suivante:
```python
import pandas as pd
```

Pandas fournit deux structures de données :
- `pd.DataFrame` représente une table de données, dans laquelle chaque colonne a un nom et chaque ligne est repérée par un index ;
- `pd.Series` représente une colonne de cette table.

__DataFrame__

Un objet de type `pd.DataFrame` représente une table dans laquelle chaque colonne a un nom et contient des objets d'un type donné (entier, réel, chaîne de caractères, etc.).

![dataframe](../images/dataframe.png)


On peut créer un DataFrame 
- soit à partir de listes de données :

In [99]:
import pandas as pd
pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]],index=[1, 2, 3],columns=['a', 'b', 'c'])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

- soit à partir d'un tableau multidimensionnel (de type `ndarray`) :

In [100]:
import numpy as np
data = np.array([[4, 7, 10],[5, 8, 11],[6, 9, 12]])
pd.DataFrame(data,index=[1, 2, 3],columns=['a', 'b', 'c'])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

- soit à partir d'une dictionnaire :

In [101]:
pd.DataFrame({'a':[4, 7, 10], 'b':[5, 8, 11], 'c':[6, 9, 12]},index=[1, 2, 3])

    a   b   c
1   4   5   6
2   7   8   9
3  10  11  12

- soit à partir d'un fichier csv

In [102]:
col_names = ['id',"hair", "feathers", 'eggs', 'milk', 'airborne', 'aquatic', 'predator','toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tails', 'domestic', 'catsize','type']
zoo = pd.read_csv('../data/zoo.data',index_col=0,names=col_names)
zoo

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wallaby,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1,1
wasp,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0,6
wolf,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
worm,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,7
wren,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2

Les données d'un DataFrame sont stockées dans un `ndarray`:

In [103]:
zoo.columns, zoo.index, zoo.values, type(zoo.values)

(Index(['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator',
        'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tails',
        'domestic', 'catsize', 'type'],
       dtype='object'),
 Index(['aardvark', 'antelope', 'bass', 'bear', 'boar', 'buffalo', 'calf',
        'carp', 'catfish', 'cavy',
        ...
        'tuatara', 'tuna', 'vampire', 'vole', 'vulture', 'wallaby', 'wasp',
        'wolf', 'worm', 'wren'],
       dtype='object', name='id', length=101),
 array([[1, 0, 0, ..., 0, 1, 1],
        [1, 0, 0, ..., 0, 1, 1],
        [0, 0, 1, ..., 0, 0, 4],
        ...,
        [1, 0, 0, ..., 0, 1, 1],
        [0, 0, 1, ..., 0, 0, 7],
        [0, 1, 1, ..., 0, 0, 2]], shape=(101, 17)),
 numpy.ndarray)

__Series__

Chaque colonne d'un DataFrame est un objet de type `pd.Series`, qui représente une série de données avec son nom de série et un index pour ses valeurs.

![series](../images/series.png)

Par exemple, la colonne "eggs" de la table `zoo` est une série de valeurs entières indexées par les noms d'animaux (qui est l'index de la table elle-même).

In [104]:
s = zoo['eggs']
s, type(s), s.index, s.values

(id
 aardvark    0
 antelope    0
 bass        1
 bear        0
 boar        0
            ..
 wallaby     0
 wasp        1
 wolf        0
 worm        1
 wren        1
 Name: eggs, Length: 101, dtype: int64,
 pandas.core.series.Series,
 Index(['aardvark', 'antelope', 'bass', 'bear', 'boar', 'buffalo', 'calf',
        'carp', 'catfish', 'cavy',
        ...
        'tuatara', 'tuna', 'vampire', 'vole', 'vulture', 'wallaby', 'wasp',
        'wolf', 'worm', 'wren'],
       dtype='object', name='id', length=101),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1]))

Pour créer une série, on crée un objet de type `pd.Series` en lui passant une séquence de valeurs et un index pour ces valeurs :

In [105]:
pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

a   -1.195685
b   -0.137717
c   -1.798905
d    1.908145
e   -0.845794
dtype: float64

<a id="index"></a>
### Index

Les lignes d'une table sont identifiées de manière unique à l'aide d'un index (qui joue un peu le rôle d'une clé primaire, comme dans le modèle relationel).

In [106]:
df = pd.DataFrame(data=[['Jean', 55], ['Marc', 40], ['Inaya', 84], ['Eva', 31]],columns=['nom','age'], index=[1, 4, 7, 10])
df['id_patient'] = ['CFX_88','CFX_00','CFX_21','E_38' ]
df = df.set_index('id_patient')
df

              nom  age
id_patient
CFX_88       Jean   55
CFX_00       Marc   40
CFX_21      Inaya   84
E_38          Eva   31

In [107]:
df.filter(regex='^CFX', axis=0)

              nom  age
id_patient
CFX_88       Jean   55
CFX_00       Marc   40
CFX_21      Inaya   84

In [108]:
df = pd.DataFrame({'month': [1, 4, 7, 10],'year': [2012, 2014, 2013, 2014],'sale': [55, 40, 84, 31]})
df, df.index

(   month  year  sale
 0      1  2012    55
 1      4  2014    40
 2      7  2013    84
 3     10  2014    31,
 RangeIndex(start=0, stop=4, step=1))

__Définir / modifier l'index__

On peut modifier un index à l'aide des fonctions 
[set_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html#pandas.DataFrame.set_index)
et [reset_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html#pandas.DataFrame.reset_index)

La fonction `set_index` permet de choisir la (ou les) colonne(s) qui serviront d'index :

In [109]:
df.set_index('month')

       year  sale
month
1      2012    55
4      2014    40
7      2013    84
10     2014    31

In [110]:
df.set_index(['year','month'])

            sale
year month
2012 1        55
2014 4        40
2013 7        84
2014 10       31

La fonction `reset_index` permet de réinitialiser l'index à l'index par défaut (numérotation 1, 2, 3...).

Par défaut, Pandas ajoute une colonne index :

In [111]:
df.reset_index()

   index  month  year  sale
0      0      1  2012    55
1      1      4  2014    40
2      2      7  2013    84
3      3     10  2014    31

L'option `drop=True` permet de ne pas ajouter cette colonne :

In [112]:
df.reset_index(drop=True)

   month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

La fonction renvoie la nouvelle DataFrame, sauf si l'option `inplace=True` est ajoutée. Dans ce cas, la modification de l'index se fait sur place, et la fonction renvoie None :

In [113]:
df.reset_index(drop=True, inplace=True)

<a id="selection"></a>
### Sélection / projection

__Sélection par index__

Plusieurs méthodes peuvent être appelées sur un objet de type `pd.DataFrame` pour sélectionner certaines lignes, certaines colonnes, ou accéder à des valeurs par leur index :
- `df.iloc[]` permet de faire de la __sélection par numéro__ de ligne ou colonne :

In [114]:
# la 4e ligne seulement
zoo.iloc[3]

hair        1
feathers    0
eggs        0
milk        1
airborne    0
aquatic     0
predator    1
toothed     1
backbone    1
breathes    1
venomous    0
fins        0
legs        4
tails       0
domestic    0
catsize     1
type        1
Name: bear, dtype: int64

In [115]:
# les 5 premières lignes, pour les colonnes de eggs à aquatic
zoo.iloc[:5,2:6]

          eggs  milk  airborne  aquatic
id
aardvark     0     1         0        0
antelope     0     1         0        0
bass         1     0         0        1
bear         0     1         0        0
boar         0     1         0        0

- `df.loc[]` permet de faire de la __sélection par label__ de ligne ou colonne

In [116]:
# la même chose, mais sélection par label
zoo.loc[:'boar','eggs':'aquatic']

          eggs  milk  airborne  aquatic
id
aardvark     0     1         0        0
antelope     0     1         0        0
bass         1     0         0        1
bear         0     1         0        0
boar         0     1         0        0

- `df.at` et `df.iat` permet d'accéder à une seule valeur étant donné son index

In [117]:
# la valeur à la ligne 1 colonne 4
zoo.iat[1,4]

np.int64(0)

In [118]:
# la même chose avec des labels
zoo.at['antelope','airborne']

np.int64(0)

__Requêtes__

Les méthodes `df.loc[]` et `df.query()` peuvent être utilisées pour sélectionner les lignes qui satisfont plusieurs conditions, à la manière d'une clause WHERE :

In [119]:
zoo.loc[(zoo['legs'] == 4) & (zoo['aquatic'] == 1)]

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
crab,0,0,1,0,0,1,1,0,0,0,0,0,4,0,0,0,7
frog,0,0,1,0,0,1,1,1,1,1,0,0,4,0,0,0,5
frog,0,0,1,0,0,1,1,1,1,1,1,0,4,0,0,0,5
mink,1,0,0,1,0,1,1,1,1,1,0,0,4,1,0,1,1
newt,0,0,1,0,0,1,1,1,1,1,0,0,4,1,0,0,5
platypus,1,0,1,1,0,1,1,0,1,1,0,0,4,1,0,1,1
toad,0,0,1,0,0,1,0,1,1,1,0,0,4,0,0,0,5

In [120]:
zoo.query('legs == 4 and aquatic == 1')

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
crab,0,0,1,0,0,1,1,0,0,0,0,0,4,0,0,0,7
frog,0,0,1,0,0,1,1,1,1,1,0,0,4,0,0,0,5
frog,0,0,1,0,0,1,1,1,1,1,1,0,4,0,0,0,5
mink,1,0,0,1,0,1,1,1,1,1,0,0,4,1,0,1,1
newt,0,0,1,0,0,1,1,1,1,1,0,0,4,1,0,0,5
platypus,1,0,1,1,0,1,1,0,1,1,0,0,4,1,0,1,1
toad,0,0,1,0,0,1,0,1,1,1,0,0,4,0,0,0,5

La méthode `df.loc[]` est généralement plus rapide, mais quelque fois moins lisible...

__Filtrer l'index (ou les noms de colonnes)__

La méthode `df.filter()` permet de filtrer l'index ou les noms de colonnes, par exemple pour 
- ne garder que les animaux qui commencent par `m` :

In [121]:
zoo.filter(regex='^m', axis=0)

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
mink,1,0,0,1,0,1,1,1,1,1,0,0,4,1,0,1,1
mole,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,0,1
mongoose,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
moth,1,0,1,0,1,0,0,0,0,1,0,0,6,0,0,0,6

- ne garder que les attributs qui contiennent `size`:

In [122]:
zoo.filter(regex='.*size',axis=1)

          catsize
id
aardvark        1
antelope        1
bass            0
bear            1
boar            1
...           ...
wallaby         1
wasp            0
wolf            1
worm            0
wren            0

[101 rows x 1 columns]

<a id="reorganiser"></a>
### Réorganiser les données

Pandas fournit de nombreuses fonctions pour [consolider, fusionner](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html) les données, comme par exemple :
- `concat()` pour mettre bout à bout deux tables

In [123]:
df1 = pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]],index=[1, 2, 3],columns=['a', 'b', 'c'])
df1

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [124]:
df2 = pd.DataFrame([[21,23,25]],index=[4],columns=['a', 'b', 'c'])
df2

    a   b   c
4  21  23  25

In [125]:
pd.concat([df1,df2])

    a   b   c
1   4   7  10
2   5   8  11
3   6   9  12
4  21  23  25

- `join` pour faire un jointure (comme en SQL), mais sur les index seulement :

In [126]:
d_df = pd.DataFrame([[21],[8]],index=[1,2],columns=['d'])
d_df

    d
1  21
2   8

In [127]:
df1.join(d_df)

   a  b   c     d
1  4  7  10  21.0
2  5  8  11   8.0
3  6  9  12   NaN

- `merge` pour faire aussi des jointures sur les colonnes (comme ici sur la colonne `b`)

In [128]:
d_df = pd.DataFrame([['ours'],['caribou']],index=[7,9],columns=['label for b'])
d_df

  label for b
7        ours
9     caribou

In [129]:
pd.merge(df1,d_df,left_on='b',right_index=True)

   a  b   c label for b
1  4  7  10        ours
3  6  9  12     caribou

- `assign()` pour créer une nouvelle colonne et la remplir

In [130]:
df1.assign(d=lambda some_df: some_df.a + 4) # ou df.assign(**{'d':(lambda some_df: some_df.a + 4)})

   a  b   c   d
1  4  7  10   8
2  5  8  11   9
3  6  9  12  10

Pandas fournit aussi des fonctions pour [résumer ou réorganiser les données](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html), comme par exemple :
- `pivot_table` qui produit un tableau croisé

In [131]:
df = pd.DataFrame({'id':['E'+str(i) for i in range(1,7)],
                   'groupe':['A','A','B','A','B','A'],
                   'note':[3,18,9,1,19,10]}).set_index('id')
df

   groupe  note
id
E1      A     3
E2      A    18
E3      B     9
E4      A     1
E5      B    19
E6      A    10

In [132]:
pd.pivot_table(df,index='groupe',values='note',aggfunc='mean')

        note
groupe
A        8.0
B       14.0

- ou `groupby` qui permet de regrouper les lignes selon les modalités d'une variable avant d'appeler une fonction d'aggrégation, comme en SQL :

In [133]:
df.groupby('groupe')['note'].max()

groupe
A    18
B    19
Name: note, dtype: int64

<a id="exercices"></a>
### Exercices

Voici des tables dont chaque ligne représente un patient pris en charge dans un des hôpitaux `CFX` (Charles Foix) ou `E` (Evry :)

In [134]:
patients = pd.DataFrame( 
	data =[
		['Jean',55,238.457299,34.49927,942.3076923],
		['Marc',40,170.79,29.21608,655.5555556],
		['Inaya',84,425.7723,36.89941,],
		['Ranim',31,329.48120,37.94897,915.8333333], 
		['Uttam',76,401.3499,39.22341,887.1065]],
	columns =['nom','age','S18','S19','S52'], 
	index =[1 , 4, 7, 10, 19] 
)

nouveaux = pd.DataFrame(
    data={
        'nom':['Thalya','Ivan'],
        'age':[29,55],
        'S18':[332.1382,537.2535],
        'S19':[44.23629,22.54623],
        'S52':[400.876256,622.535622],
    },
    index = ['CFX_35','E_18']
)

identifiants = ['CFX_88','CFX_00','CFX_21','E_38', 'E_12']

Quel est le type de données de l'objet Python référencé par le nom `patients` ?

Afficher également les valeurs, les noms de colonne et l'index de la table `patients`.

In [135]:
# <- completer ici

Dans la table `patients`, ajouter une colonne appelée ̀`id_patient`, dans laquelle on placera les
valeurs de la liste `identifiants`. Faire de cette nouvelle colonne l’index de la table. 
On doit obtenir :

<img src="../images/patients_index.png" />

In [ ]:
# <- completer ici

Un objet de type Series représente une série de données (une colonne ou une ligne d’une table).
Afficher successivement les valeurs, l’index, et le nom des séries suivantes :
- la colonne `age` de la table patients ;
- la 3ème ligne de la table patients.

In [ ]:
# <- completer ici

Utiliser la fonction `pd.concat` pour mettre bout à bout la table `patients` et la table `nouveaux`.

In [ ]:
# <- completer ici

On veut maintenant sélectionner certaines lignes ou colonnes de la table. En particulier, on
voudrait les valeurs des attributs numériques (`S18`, `S19`, `S52`) pour les patients de plus de 50 ans.

Pour cela, une façon de procéder (un peu fastidieuse) serait d'utiliser la méthode de sélection par label en lui passant deux listes de Booléens qui spécifient les lignes et les colonnes qu'on veut :

In [ ]:
condition_lignes = [True, False, True, False, True, False, True]
condition_colonnes = [True, False, True, False, True]
patients.loc[condition_lignes,condition_colonnes]

Tester cette méthode et vérifier que cette instruction donne bien le bon résultat.

Une manière plus efficace consiste à définir des conditions plus explicites
et à les utiliser dans la méthode de sélection par label, par exemple :

In [ ]:
condition_age = patients['age'] > 50
condition_num = ['S18', 'S19', 'S52']
patients.loc[condition_age, condition_num]

Quel est l'âge de Marc ?

In [ ]:
# <- completer ici

Changer l'âge de Marc pour qu'il soit âgé de 92 ans.

In [ ]:
# <- completer ici

On veut comparer l'âge moyen des patients de Charles Foix avec l'âge moyen des patients d'Evry.

A l'aide des fonction `filter` et `assign` ajouter une colonne `hopital` dans laquelle on mettra ̀`C` si le patient est de Charles Foix, et `E` si le patient est d'Evry.

In [ ]:
# <- completer ici

A l'aide de la fonction  `pivot_table`, faire un tableau croisé pour calculer l'âge moyen des patients de chaque hôpital.

In [ ]:
# <- completer ici

Utiliser la méthode de sélection par label pour sélectionner toutes les lignes du jeu
de données iris qui décrivent des fleurs de l’espèce setosa.

Faites de même pour les deux autres espèces, virginica et versicolor.

Combien y a-t-il de fleurs de chaque espèce ?

In [ ]:
# <- completer ici