## Comment utiliser ce notebook
Cliquer sur une cellule et presser Entrée pour éditer une cellule.<br/>
Appuyer sur Shift+Entrée pour exécuter la cellule.<br/>
Pour répondre à un exercice, remplacer la ligne
```python
# <- completer ici
```
par votre code et exécuter la cellule.
<hr/>

### Pandas

La librairie [Pandas](https://pandas.pydata.org/) est une librairie d'analyse de données utilisée pour manipuler des données tabulaires.

Sous-sections :
[Séries et DataFrames](#dataframes)&nbsp;|
[Index](#index)&nbsp;|
[Sélections et projections](#selection)&nbsp;|
[Décrire un jeu de données](#decrire)&nbsp;|
[Réorganiser les données](#reorganiser)&nbsp;|
[Exercices](#exercices)&nbsp;

<a id="dataframes"></a>
### Séries et DataFrames

On importe généralement le module Pandas de la manière suivante:
```python
import pandas as pd
```

Pandas fournit deux structures de données :
- `pd.DataFrame` représente une table de données, dans laquelle chaque colonne a un nom et chaque ligne est repérée par un index ;
- `pd.Series` représente une colonne de cette table.

__DataFrame__

Un objet de type `pd.DataFrame` représente une table dans laquelle chaque colonne a un nom et contient des objets d'un type donné (entier, réel, chaîne de caractères, etc.).

![dataframe](../images/dataframe.png)


On peut créer un DataFrame 
- soit à partir de listes de données :

In [2]:
import pandas as pd
pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]],index=[1, 2, 3],columns=['a', 'b', 'c'])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

- soit à partir d'un tableau multidimensionnel (de type `ndarray`) :

In [3]:
import numpy as np
data = np.array([[4, 7, 10],[5, 8, 11],[6, 9, 12]])
pd.DataFrame(data,index=[1, 2, 3],columns=['a', 'b', 'c'])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

- soit à partir d'une dictionnaire :

In [4]:
pd.DataFrame({'a':[4, 7, 10], 'b':[5, 8, 11], 'c':[6, 9, 12]},index=[1, 2, 3])

    a   b   c
1   4   5   6
2   7   8   9
3  10  11  12

- soit à partir d'un fichier csv

In [5]:
col_names = ['id',"hair", "feathers", 'eggs', 'milk', 'airborne', 'aquatic', 'predator','toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tails', 'domestic', 'catsize','type']
zoo = pd.read_csv('../data/zoo.data',index_col=0,names=col_names)
zoo

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wallaby,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1,1
wasp,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0,6
wolf,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
worm,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,7
wren,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2

Les données d'un DataFrame sont stockées dans un `ndarray`:

In [6]:
zoo.columns, zoo.index, zoo.values, type(zoo.values)

(Index(['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator',
        'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tails',
        'domestic', 'catsize', 'type'],
       dtype='object'),
 Index(['aardvark', 'antelope', 'bass', 'bear', 'boar', 'buffalo', 'calf',
        'carp', 'catfish', 'cavy',
        ...
        'tuatara', 'tuna', 'vampire', 'vole', 'vulture', 'wallaby', 'wasp',
        'wolf', 'worm', 'wren'],
       dtype='object', name='id', length=101),
 array([[1, 0, 0, ..., 0, 1, 1],
        [1, 0, 0, ..., 0, 1, 1],
        [0, 0, 1, ..., 0, 0, 4],
        ...,
        [1, 0, 0, ..., 0, 1, 1],
        [0, 0, 1, ..., 0, 0, 7],
        [0, 1, 1, ..., 0, 0, 2]]),
 numpy.ndarray)

__Series__

Chaque colonne d'un DataFrame est un objet de type `pd.Series`, qui représente une série de données avec son nom de série et un index pour ses valeurs.

![series](../images/series.png)

Par exemple, la colonne "eggs" de la table `zoo` est une série de valeurs entières indexées par les noms d'animaux (qui est l'index de la table elle-même).

In [7]:
s = zoo['eggs']
s, type(s), s.index, s.values

(id
 aardvark    0
 antelope    0
 bass        1
 bear        0
 boar        0
            ..
 wallaby     0
 wasp        1
 wolf        0
 worm        1
 wren        1
 Name: eggs, Length: 101, dtype: int64,
 pandas.core.series.Series,
 Index(['aardvark', 'antelope', 'bass', 'bear', 'boar', 'buffalo', 'calf',
        'carp', 'catfish', 'cavy',
        ...
        'tuatara', 'tuna', 'vampire', 'vole', 'vulture', 'wallaby', 'wasp',
        'wolf', 'worm', 'wren'],
       dtype='object', name='id', length=101),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1]))

Pour créer une série, on crée un objet de type `pd.Series` en lui passant une séquence de valeurs et un index pour ces valeurs :

In [8]:
pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

a    0.071533
b    0.197959
c    0.964285
d   -0.339248
e    0.232197
dtype: float64

<a id="index"></a>
### Index

Les lignes d'une table sont identifiées de manière unique à l'aide d'un index (qui joue un peu le rôle d'une clé primaire, comme dans le modèle relationel).

In [9]:
df = pd.DataFrame({'month': [1, 4, 7, 10],'year': [2012, 2014, 2013, 2014],'sale': [55, 40, 84, 31]})
df, df.index

(   month  year  sale
 0      1  2012    55
 1      4  2014    40
 2      7  2013    84
 3     10  2014    31,
 RangeIndex(start=0, stop=4, step=1))

__Définir / modifier l'index__

On peut modifier un index à l'aide des fonctions 
[set_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html#pandas.DataFrame.set_index)
et [reset_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html#pandas.DataFrame.reset_index)

La fonction `set_index` permet de choisir la (ou les) colonne(s) qui serviront d'index :

In [10]:
df.set_index('month')

       year  sale
month
1      2012    55
4      2014    40
7      2013    84
10     2014    31

In [11]:
df.set_index(['year','month'])

            sale
year month
2012 1        55
2014 4        40
2013 7        84
2014 10       31

La fonction `reset_index` permet de réinitialiser l'index à l'index par défaut (numérotation 1, 2, 3...).

Par défaut, Pandas ajoute une colonne index :

In [12]:
df.reset_index()

   index  month  year  sale
0      0      1  2012    55
1      1      4  2014    40
2      2      7  2013    84
3      3     10  2014    31

L'option `drop=True` permet de ne pas ajouter cette colonne :

In [13]:
df.reset_index(drop=True)

   month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

La fonction renvoie la nouvelle DataFrame, sauf si l'option `inplace=True` est ajoutée. Dans ce cas, la modification de l'index se fait sur place, et la fonction renvoie None :

In [14]:
df.reset_index(drop=True, inplace=True)

<a id="selection"></a>
### Sélection / projection

__Sélection par index__

Plusieurs méthodes peuvent être appelées sur un objet de type `pd.DataFrame` pour sélectionner certaines lignes, certaines colonnes, ou accéder à des valeurs par leur index :
- `df.iloc[]` permet de faire de la __sélection par numéro__ de ligne ou colonne :

In [15]:
# la 4e ligne seulement
zoo.iloc[3]

hair        1
feathers    0
eggs        0
milk        1
airborne    0
aquatic     0
predator    1
toothed     1
backbone    1
breathes    1
venomous    0
fins        0
legs        4
tails       0
domestic    0
catsize     1
type        1
Name: bear, dtype: int64

In [16]:
# les 5 premières lignes, pour les colonnes de eggs à aquatic
zoo.iloc[:5,2:6]

          eggs  milk  airborne  aquatic
id
aardvark     0     1         0        0
antelope     0     1         0        0
bass         1     0         0        1
bear         0     1         0        0
boar         0     1         0        0

- `df.loc[]` permet de faire de la __sélection par label__ de ligne ou colonne

In [17]:
# la même chose, mais sélection par label
zoo.loc[:'boar','eggs':'aquatic']

          eggs  milk  airborne  aquatic
id
aardvark     0     1         0        0
antelope     0     1         0        0
bass         1     0         0        1
bear         0     1         0        0
boar         0     1         0        0

- `df.at` et `df.iat` permet d'accéder à une seule valeur étant donné son index

In [18]:
# la valeur à la ligne 1 colonne 4
zoo.iat[1,4]

0

In [19]:
# la même chose avec des labels
zoo.at['antelope','airborne']

0

__Requêtes__

Les méthodes `df.loc[]` et `df.query()` peuvent être utilisées pour sélectionner les lignes qui satisfont plusieurs conditions, à la manière d'une clause WHERE :

In [20]:
zoo.loc[(zoo['legs'] == 4) & (zoo['aquatic'] == 1)]

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
crab,0,0,1,0,0,1,1,0,0,0,0,0,4,0,0,0,7
frog,0,0,1,0,0,1,1,1,1,1,0,0,4,0,0,0,5
frog,0,0,1,0,0,1,1,1,1,1,1,0,4,0,0,0,5
mink,1,0,0,1,0,1,1,1,1,1,0,0,4,1,0,1,1
newt,0,0,1,0,0,1,1,1,1,1,0,0,4,1,0,0,5
platypus,1,0,1,1,0,1,1,0,1,1,0,0,4,1,0,1,1
toad,0,0,1,0,0,1,0,1,1,1,0,0,4,0,0,0,5

In [21]:
zoo.query('legs == 4 and aquatic == 1')

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
crab,0,0,1,0,0,1,1,0,0,0,0,0,4,0,0,0,7
frog,0,0,1,0,0,1,1,1,1,1,0,0,4,0,0,0,5
frog,0,0,1,0,0,1,1,1,1,1,1,0,4,0,0,0,5
mink,1,0,0,1,0,1,1,1,1,1,0,0,4,1,0,1,1
newt,0,0,1,0,0,1,1,1,1,1,0,0,4,1,0,0,5
platypus,1,0,1,1,0,1,1,0,1,1,0,0,4,1,0,1,1
toad,0,0,1,0,0,1,0,1,1,1,0,0,4,0,0,0,5

La méthode `df.loc[]` est généralement plus rapide, mais quelque fois moins lisible...

__Filtrer l'index (ou les noms de colonnes)__

La méthode `df.filter()` permet de filtrer l'index ou les noms de colonnes, par exemple pour 
- ne garder que les animaux qui commencent par `m` :

In [22]:
zoo.filter(regex='^m', axis=0)

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
mink,1,0,0,1,0,1,1,1,1,1,0,0,4,1,0,1,1
mole,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,0,1
mongoose,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
moth,1,0,1,0,1,0,0,0,0,1,0,0,6,0,0,0,6

- ne garder que les attributs qui contiennent `size`:

In [23]:
zoo.filter(regex='.*size',axis=1)

          catsize
id
aardvark        1
antelope        1
bass            0
bear            1
boar            1
...           ...
wallaby         1
wasp            0
wolf            1
worm            0
wren            0

[101 rows x 1 columns]

<a id="decrire"></a>
### Décrire un jeu de données

`df.head()` affiche les premières lignes du jeu de données :

In [24]:
zoo.head()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tails,domestic,catsize,type
id,,,,,,,,,,,,,,,,,
aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

Pour chaque attribut, on peut lister quelques statistiques (nombre de valeurs, moyenne, médiane, Q1, Q3, écart type, max) :

In [25]:
df = pd.DataFrame(
    {"month": [1, 4, 7, 10], "year": [2012, 2014, 2013, 2014], "sale": [55, 40, 84, 31]}
)
df

   month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [26]:
df.describe()

           month         year       sale
count   4.000000     4.000000   4.000000
mean    5.500000  2013.250000  52.500000
std     3.872983     0.957427  23.216374
min     1.000000  2012.000000  31.000000
25%     3.250000  2012.750000  37.750000
50%     5.500000  2013.500000  47.500000
75%     7.750000  2014.000000  62.250000
max    10.000000  2014.000000  84.000000

On peut aussi obtenir pour chaque attribut la liste des modalités de l'attribut :

In [27]:
df['year'].unique()

array([2012, 2014, 2013])

ainsi que l'effectif pour chaque modalité :

In [28]:
df['year'].value_counts()

year
2014    2
2012    1
2013    1
Name: count, dtype: int64

__Valeurs manquantes__

Les valeurs manquantes (notées `NaN` dans un tableau numérique) peuvent être détectées à l'aide de la fonction `pd.isna` :

In [29]:
df.loc[1,'sale']=np.nan
df, pd.isna(df)

(   month  year  sale
 0      1  2012  55.0
 1      4  2014   NaN
 2      7  2013  84.0
 3     10  2014  31.0,
    month   year   sale
 0  False  False  False
 1  False  False   True
 2  False  False  False
 3  False  False  False)

Il y a plusieurs moyens de traiter les valeurs manquantes :
- soit on enlève l'instance toute entière

In [30]:
df.dropna()

   month  year  sale
0      1  2012  55.0
2      7  2013  84.0
3     10  2014  31.0

- soit on attribue la valeur moyenne sur le jeu de données

In [31]:
df.fillna(df.mean(0)['sale'])

   month  year       sale
0      1  2012  55.000000
1      4  2014  56.666667
2      7  2013  84.000000
3     10  2014  31.000000

<a id="reorganiser"></a>
### Réorganiser les données

Pandas fournit de nombreuses fonctions pour [consolider, fusionner](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html) les données, comme par exemple :
- `concat()` pour mettre bout à bout deux tables

In [32]:
df1 = pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]],index=[1, 2, 3],columns=['a', 'b', 'c'])
df1

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [33]:
df2 = pd.DataFrame([[21,23,25]],index=[4],columns=['a', 'b', 'c'])
df2

    a   b   c
4  21  23  25

In [34]:
pd.concat([df1,df2])

    a   b   c
1   4   7  10
2   5   8  11
3   6   9  12
4  21  23  25

- `join` pour faire un jointure (comme en SQL), mais sur les index seulement :

In [35]:
d_df = pd.DataFrame([[21],[8]],index=[1,2],columns=['d'])
d_df

    d
1  21
2   8

In [36]:
df1.join(d_df)

   a  b   c     d
1  4  7  10  21.0
2  5  8  11   8.0
3  6  9  12   NaN

- `merge` pour faire aussi des jointures sur les colonnes (comme ici sur la colonne `b`)

In [37]:
d_df = pd.DataFrame([['ours'],['caribou']],index=[7,9],columns=['label for b'])
d_df

  label for b
7        ours
9     caribou

In [38]:
pd.merge(df1,d_df,left_on='b',right_index=True)

   a  b   c label for b
1  4  7  10        ours
3  6  9  12     caribou

- `assign()` pour créer une nouvelle colonne et la remplir

In [39]:
df1.assign(d=lambda some_df: some_df.a + 4) # ou df.assign(**{'d':(lambda some_df: some_df.a + 4)})

   a  b   c   d
1  4  7  10   8
2  5  8  11   9
3  6  9  12  10

Pandas fournit aussi des fonctions pour [résumer ou réorganiser les données](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html), comme par exemple :
- `pivot_table` qui produit un tableau croisé

In [ ]:
df = pd.DataFrame({'id':['E'+str(i) for i in range(1,7)],
                   'groupe':['A','A','B','A','B','A'],
                   'note':[3,18,9,1,19,10]}).set_index('id')
df

   groupe  note
id
E1      A     3
E2      A    18
E3      B     9
E4      A     1
E5      B    19
E6      A    10

In [ ]:
pd.pivot_table(df,index='groupe',values='note',aggfunc='mean')

        note
groupe
A        8.0
B       14.0

- ou `groupby` qui permet de regrouper les lignes selon les modalités d'une variable avant d'appeler une fonction d'aggrégation, comme en SQL :

In [ ]:
df.groupby('groupe')['note'].max()

groupe
A    18
B    19
Name: note, dtype: int64

<a id="exercices"></a>
### Exercices

Le jeu de données [Breast Cancer Wisconsin](https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original) contient 699 instances décrivant des patients atteints du cancer du sein.

Dans ce jeu de données, 
chaque patient est décrit par ses résultats de tests de cytopathologie, et sa tumeur est classifiée dans l'une des deux classes `2` (Benign) ou `4` (Malignant).

Le jeu de données est souvent utilisé pour tester des algorithmes de classification, dans lesquels la tâche consiste à prédire la classe d'un nouveau patient à partir de sa description.

Le fichier `breast-cancer-wisconsin.data` contient les données au format csv.
La première colonne est un identifiant unique, les 9 suivantes sont des attributs descriptifs de la cytologie du patient, et le dernier est la classe.  

Nous voulons charger, nettoyer ces données, puis appliquer l'algorithme $k$-NN.

__Chargement des données__

__Exercice__.
Charger les données dans une `pd.DataFrame`.
Faire en sorte que la colonne `id` constitue l'index de la DataFrame obtenue.

In [42]:
features = ['id', 'clump', 'uniformity_cell_size', 'uniformity_cell_shape', 'marginal_adhesion','single_epithelial_cell_size', 'bare_nuclei', 'chromatin', 'normal_nucleoli', 'mitoses']
cls_att = 'class'

# <- completer ici
df

  id_etudiant groupe  note
0          E1      A     3
1          E2      A    18
2          E3      B     9
3          E4      A     1
4          E5      B    19
5          E6      A    10

__Exploration du jeu de données__

__Exercice__.
Quelles sont les valeurs prises par l'attribut `class` ?

In [43]:
# <- completer ici

__Exercice__.
Combien y a-t-il d'instances de chaque classe ?

In [44]:
# <- completer ici

__Exercice__.
Calculer la moyenne et la variance de chaque attribut et rassembler les résultats dans une table comme celle-ci :

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Moyenne</th>
      <th>Variance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>clump</th>
      <td>4.442167</td>
      <td>7.945045</td>
    </tr>
    <tr>
      <th>uniformity_cell_size</th>
      <td>3.150805</td>
      <td>9.381357</td>
    </tr>
    <tr>
      <th>uniformity_cell_shape</th>
      <td>3.215227</td>
      <td>8.918538</td>
    </tr>
    <tr>
      <th>marginal_adhesion</th>
      <td>2.830161</td>
      <td>8.193702</td>
    </tr>
    <tr>
      <th>single_epithelial_cell_size</th>
      <td>3.234261</td>
      <td>4.934873</td>
    </tr>
    <tr>
      <th>bare_nuclei</th>
      <td>3.544656</td>
      <td>13.258255</td>
    </tr>
    <tr>
      <th>chromatin</th>
      <td>3.445095</td>
      <td>5.992227</td>
    </tr>
    <tr>
      <th>normal_nucleoli</th>
      <td>2.869693</td>
      <td>9.305128</td>
    </tr>
    <tr>
      <th>mitoses</th>
      <td>1.603221</td>
      <td>2.997764</td>
    </tr>
    <tr>
      <th>class</th>
      <td>2.699854</td>
      <td>0.909912</td>
    </tr>
  </tbody>
</table>
</div>

In [45]:
# <- completer ici

__Nettoyage des données__

__Exercice__.
Combien y a-t-il de valeurs manquantes dans ce jeu de données ?

In [46]:
# <- completer ici

__Exercice__.
Retirer du jeu de données les instances contenant des valeurs manquantes.

In [47]:
# <- completer ici

__Application de l'algorithme kNN__

On veut maintenant tester l'algorithme des $k$ plus proches voisins sur le jeu de données Breast Cancer Wisconsin.

__Exercice__.
A l'aide des fonctions `df.sample()` et `df.drop()`, diviser le jeu de données en deux :
- un jeu de test de $200$ instances
- une base de cas contenant le reste des instances

In [48]:
# <- completer ici
# test = ...
# cb = ...

__Exercice__.
Extraire du jeu de test deux objets de type `np.ndarray` appelés `X_test` et `y_test`, et contenant respectivement les entrées et les sorties du jeu de test.

In [49]:
# <- completer ici
# X_test = ...
# y_test = ...

__Exercice__.
Extraire de même de la base de cas deux objets `X` et `y` du type `np.ndarray` contenant les entrées et les sorties de la base de cas.

In [50]:
# <- completer ici
# X = ...
# y = ...

__Exercice__ 
Utiliser le module `knn` développé aux TPs précédents pour calculer le taux de bonnes réponses de l'algorithme $k$-NN avec les paramètres suivants :
- jeu de test T = (`X_test`,`y_test`)
- base de cas CB = (`X`,`y`) 
- mesure de similarité $\sigma_S =$ `euclidean_sim`
- $k=3$

Remarque : si la liste `pred` contient les réponses prédites pour chacunes des entrées de `X_test`, le taux de bonnes réponses `acc` peut être calculé de la manière suivante :
```python
acc = np.mean(np.array(pred) == y_test)
```

In [51]:
# <- completer ici